const conn = require("./../connection/connection");
const { Player, Team } = require("./../models");

async function run() {
  const teams = [
    {
      name: "Arizona Cardinals",
      rating: 70,
    },
    {
      name: "Atlanta Falcons",
      rating: 78,
    },
    {
      name: "Carolina Panthers",
      rating: 76,
    },
    {
      name: "Chicago Bears",
      rating: 68,
    },
    {
      name: "Dallas Cowboys",
      rating: 90,
    },
    {
      name: "Detroit Lions",
      rating: 86,
    },
    {
      name: "Green Bay Packers",
      rating: 85,
    },
    {
      name: "Los Angeles Rams",
      rating: 73,
    },
    {
      name: "Minnesota Vikings",
      rating: 91,
    },
    {
      name: "New Orleans Saints",
      rating: 78,
    },
    {
      name: "New York Giants",
      rating: 83,
    },
    {
      name: "Philadelphia Eagles",
      rating: 98,
    },
    {
      name: "San Francisco 49ers",
      rating: 95,
    },
    {
      name: "Seattle Seahawks",
      rating: 86,
    },
    {
      name: "Tampa Bay Buccaneers",
      rating: 85,
    },
    {
      name: "Washington Commanders",
      rating: 85,
    },
    {
      name: "Baltimore Ravens",
      rating: 92,
    },
    {
      name: "Buffalo Bills",
      rating: 96,
    },
    {
      name: "Cincinnati Bengals",
      rating: 95,
    },
    {
      name: "Cleveland Browns",
      rating: 84,
    },
    {
      name: "Denver Broncos",
      rating: 74,
    },
    {
      name: "Houston Texans",
      rating: 66,
    },
    {
      name: "Indianapolis Colts",
      rating: 70,
    },
    {
      name: "Jacksonville Jaguars",
      rating: 87,
    },
    {
      name: "Kansas City Chiefs",
      rating: 99,
    },
    {
      name: "Las Vegas Raiders",
      rating: 76,
    },
    {
      name: "Los Angeles Chargers",
      rating: 87,
    },
    {
      name: "Miami Dolphins",
      rating: 86,
    },
    {
      name: "New England Patriots",
      rating: 85,
    },
    {
      name: "New York Jets",
      rating: 84,
    },
    {
      name: "Pittsburgh Steelers",
      rating: 87,
    },
    {
      name: "Tennessee Titans",
      rating: 83,
    },
  ]

  const players = [
    {
      name: "Patrick Mahomes",
      age: 27,
      position: "Quarterback",
      team: "Kansas City Chiefs",
      rating: 105,
      passing: 5250,
      receiving: 0,
      rushing: 358,
      fumbles: 0,
      tackles: 0,
      interceptions: 12,
      touchdowns: 41,
    },

    {
      name: "Tom Brady",
      age: 44,
      position: "Quarterback",
      team: "New England Patriots",
      rating: 91,
      passing: 4694,
      receiving: 4,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 9,
      touchdowns: 25,
    },

    {
      name: "Aaron Rodgers",
      age: 39,
      position: "Quarterback",
      team: "Green Bay Packers",
      rating: 91,
      passing: 3695,
      receiving: 0,
      rushing: 94,
      fumbles: 3,
      tackles: 0,
      interceptions: 12,
      touchdowns: 26,
    },
    {
      name: "Justin Herbert",
      age: 24,
      position: "Quarterback",
      team: "Los Angeles Chargers",
      rating: 93,
      passing: 4739,
      receiving: 0,
      rushing: 147,
      fumbles: 4,
      tackles: 0,
      interceptions: 10,
      touchdowns: 25,
    },
    {
      name: "Kirk Cousins",
      age: 34,
      position: "Quarterback",
      team: "Minnesota Vikings",
      rating: 93,
      passing: 4547,
      receiving: 0,
      rushing: 97,
      fumbles: 2,
      tackles: 0,
      interceptions: 14,
      touchdowns: 29,
    },
    {
      name: "Joe Burrow",
      age: 26,
      position: "Quarterback",
      team: "Cincinnati Bengals",
      rating: 101,
      passing: 4475,
      receiving: 0,
      rushing: 257,
      fumbles: 0,
      tackles: 0,
      interceptions: 12,
      touchdowns: 35,
    },
    {
      name: "Jared Goff",
      age: 28,
      position: "Quarterback",
      team: "Detroit Lions",
      rating: 99,
      passing: 4438,
      receiving: 0,
      rushing: 73,
      fumbles: 3,
      tackles: 0,
      interceptions: 7,
      touchdowns: 29,
    },
    {
      name: "Josh Allen",
      age: 26,
      position: "Quarterback",
      team: "Buffalo Bills",
      rating: 97,
      passing: 4283,
      receiving: 0,
      rushing: 762,
      fumbles: 8,
      tackles: 0,
      interceptions: 14,
      touchdowns: 35,
    },
    {
      name: "Geno Smith",
      age: 32,
      position: "Quarterback",
      team: "Seattle Seahawks",
      rating: 101,
      passing: 4282,
      receiving: 0,
      rushing: 366,
      fumbles: 3,
      tackles: 0,
      interceptions: 11,
      touchdowns: 30,
    },
    {
      name: "Trevor Lawrence",
      age: 23,
      position: "Quarterback",
      team: "Jacksonville Jaguars",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 291,
      fumbles: 5,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Jalen Hurts",
      age: 24,
      position: "Quarterback",
      team: "Philadelphia Eagles",
      rating: 102,
      passing: 3701,
      receiving: 0,
      rushing: 760,
      fumbles: 5,
      tackles: 0,
      interceptions: 6,
      touchdowns: 22,
    },
    {
      name: "Tua Tagovailoa",
      age: 24,
      position: "Quarterback",
      team: "Miami Dolphins",
      rating: 106,
      passing: 3548,
      receiving: 0,
      rushing: 70,
      fumbles: 2,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Russell Wilson",
      age: 34,
      position: "Quarterback",
      team: "Seattle Seahawks",
      rating: 84,
      passing: 3524,
      receiving: 0,
      rushing: 277,
      fumbles: 2,
      tackles: 0,
      interceptions: 11,
      touchdowns: 16,
    },
    {
      name: "Derek Carr",
      age: 31,
      position: "Quarterback",
      team: "Las Vegas Raiders",
      rating: 86,
      passing: 3522,
      receiving: 0,
      rushing: 102,
      fumbles: 1,
      tackles: 0,
      interceptions: 14,
      touchdowns: 24,
    },
    {
      name: "Daniel Jones",
      age: 25,
      position: "Quarterback",
      team: "New York Giants",
      rating: 93,
      passing: 3205,
      receiving: 0,
      rushing: 708,
      fumbles: 2,
      tackles: 0,
      interceptions: 5,
      touchdowns: 15,
    },
    {
      name: "Davis Mills",
      age: 24,
      position: "Quarterback",
      team: "Houston Texans",
      rating: 79,
      passing: 3118,
      receiving: 0,
      rushing: 108,
      fumbles: 3,
      tackles: 0,
      interceptions: 15,
      touchdowns: 17,
    },
    {
      name: "Matt Ryan",
      age: 37,
      position: "Quarterback",
      team: "Indianapolis Colts",
      rating: 84,
      passing: 3057,
      receiving: 0,
      rushing: 70,
      fumbles: 4,
      tackles: 0,
      interceptions: 13,
      touchdowns: 14,
    },
    {
      name: "Mac Jones",
      age: 24,
      position: "Quarterback",
      team: "New England Patriots",
      rating: 85,
      passing: 2997,
      receiving: 0,
      rushing: 102,
      fumbles: 3,
      tackles: 0,
      interceptions: 11,
      touchdowns: 14,
    },
    {
      name: "Andy Dalton",
      age: 35,
      position: "Quarterback",
      team: "New Orleans Saints",
      rating: 95,
      passing: 2871,
      receiving: 0,
      rushing: 54,
      fumbles: 3,
      tackles: 0,
      interceptions: 9,
      touchdowns: 18,
    },
    {
      name: "Dak Prescott",
      age: 29,
      position: "Quarterback",
      team: "Dallas Cowboys",
      rating: 91,
      passing: 2860,
      receiving: 0,
      rushing: 182,
      fumbles: 2,
      tackles: 0,
      interceptions: 15,
      touchdowns: 23,
    },
    {
      name: "Jacoby Brissett",
      age: 30,
      position: "Quarterback",
      team: "Cleveland Browns",
      rating: 89,
      passing: 2608,
      receiving: 0,
      rushing: 243,
      fumbles: 1,
      tackles: 0,
      interceptions: 6,
      touchdowns: 12,
    },
    {
      name: "Ryan Tannehill",
      age: 34,
      position: "Quarterback",
      team: "Tenessee Titans",
      rating: 95,
      passing: 2536,
      receiving: 0,
      rushing: 98,
      fumbles: 1,
      tackles: 0,
      interceptions: 6,
      touchdowns: 13,
    },
    {
      name: "Jimmy Garoppolo",
      age: 31,
      position: "Quarterback",
      team: "San Francisco 49ers",
      rating: 103,
      passing: 2437,
      receiving: 0,
      rushing: 33,
      fumbles: 2,
      tackles: 0,
      interceptions: 4,
      touchdowns: 16,
    },
    {
      name: "Kenny Pickett",
      age: 24,
      position: "Quarterback",
      team: "Pittsburgh Steelers",
      rating: 77,
      passing: 2404,
      receiving: 0,
      rushing: 237,
      fumbles: 3,
      tackles: 0,
      interceptions: 9,
      touchdowns: 7,
    },
    {
      name: "Kyler Murray",
      age: 25,
      position: "Quarterback",
      team: "Arizona Cardinals",
      rating: 87,
      passing: 2368,
      receiving: 0,
      rushing: 418,
      fumbles: 6,
      tackles: 0,
      interceptions: 7,
      touchdowns: 14,
    },
    {
      name: "Lamar Jackson",
      age: 26,
      position: "Quarterback",
      team: "Baltimore Ravens",
      rating: 91,
      passing: 2242,
      receiving: 0,
      rushing: 764,
      fumbles: 4,
      tackles: 0,
      interceptions: 7,
      touchdowns: 17,
    },
    {
      name: "Justin Fields",
      age: 23,
      position: "Quarterback",
      team: "Chicago Bears",
      rating: 85,
      passing: 2242,
      receiving: 0,
      rushing: 1143,
      fumbles: 9,
      tackles: 0,
      interceptions: 11,
      touchdowns: 17,
    },
    {
      name: "Marcus Mariota",
      age: 29,
      position: "Quarterback",
      team: "Atlanta Falcons",
      rating: 88,
      passing: 2219,
      receiving: 0,
      rushing: 438,
      fumbles: 5,
      tackles: 0,
      interceptions: 9,
      touchdowns: 15,
    },
    {
      name: "Baker Mayfield",
      age: 27,
      position: "Quarterback",
      team: "Los Angeles Rams",
      rating: 79,
      passing: 2163,
      receiving: 0,
      rushing: 89,
      fumbles: 6,
      tackles: 0,
      interceptions: 8,
      touchdowns: 10,
    },
    {
      name: "Josh Jacobs",
      age: 25,
      position: "Running back",
      team: "Las Vegas Raiders",
      rating: 1,
      passing: 0,
      receiving: 400,
      rushing: 1653,
      fumbles: 3,
      tackles: 0,
      interceptions: 0,
      touchdowns: 12,
    },
    {
      name: "Derrick Henry",
      age: 29,
      position: "Running back",
      team: "Tennessee Titans",
      rating: 2,
      passing: 0,
      receiving: 398,
      rushing: 1538,
      fumbles: 6,
      tackles: 0,
      interceptions: 0,
      touchdowns: 13,
    },
    {
      name: "Nick Chubb",
      age: 27,
      position: "Running back",
      team: "Cleveland Browns",
      rating: 3,
      passing: 0,
      receiving: 239,
      rushing: 1525,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 13,
    },
    {
      name: "Saquon Barkley",
      age: 26,
      position: "Running back",
      team: "New York Giants",
      rating: 4,
      passing: 0,
      receiving: 338,
      rushing: 1312,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 10,
    },
    {
      name: "Miles Sanders",
      age: 25,
      position: "Running back",
      team: "Philadelphia Eagles",
      rating: 5,
      passing: 0,
      receiving: 78,
      rushing: 1268,
      fumbles: 2,
      tackles: 0,
      interceptions: 0,
      touchdowns: 11,
    },
    {
      name: "Dalvin Cook",
      age: 27,
      position: "Running back",
      team: "Minnesota Vikings",
      rating: 6,
      passing: 0,
      receiving: 295,
      rushing: 1173,
      fumbles: 4,
      tackles: 0,
      interceptions: 0,
      touchdowns: 10,
    },
    {
      name: "Christian McCarrery",
      age: 26,
      position: "Running back",
      team: "San Francisco 49ers",
      rating: 7,
      passing: 0,
      receiving: 741,
      rushing: 1139,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 13,
    },
    {
      name: "Travis Etienne Jr.",
      age: 24,
      position: "Running back",
      team: "Jacksonville Jaguars",
      rating: 8,
      passing: 0,
      receiving: 316,
      rushing: 1125,
      fumbles: 5,
      tackles: 0,
      interceptions: 0,
      touchdowns: 5,
    },
    {
      name: "Aaron Jones",
      age: 28,
      position: "Running back",
      team: "Green Bay Packers",
      rating: 9,
      passing: 0,
      receiving: 395,
      rushing: 1121,
      fumbles: 5,
      tackles: 0,
      interceptions: 0,
      touchdowns: 7,
    },
    {
      name: "Jamaal Williams",
      age: 27,
      position: "Running back",
      team: "Detroit Lions",
      rating: 10,
      passing: 0,
      receiving: 73,
      rushing: 1066,
      fumbles: 3,
      tackles: 0,
      interceptions: 0,
      touchdowns: 17,
    },
    {
      name: "Kenneth Walker III",
      age: 22,
      position: "Running back",
      team: "Seattle Seahawks",
      rating: 11,
      passing: 0,
      receiving: 165,
      rushing: 1050,
      fumbles: 0,
      tackles: 0,
      interceptions: 0,
      touchdowns: 9,
    },
    {
      name: "Rhamondre Stevenson",
      age: 24,
      position: "Running back",
      team: "New England Patriots",
      rating: 12,
      passing: 0,
      receiving: 421,
      rushing: 1040,
      fumbles: 4,
      tackles: 0,
      interceptions: 0,
      touchdowns: 6,
    },
    {
      name: "Tyler Allgeier",
      age: 22,
      position: "Running back",
      team: "Atlanta Falcons",
      rating: 13,
      passing: 0,
      receiving: 139,
      rushing: 1035,
      fumbles: 0,
      tackles: 0,
      interceptions: 0,
      touchdowns: 4,
    },
    {
      name: "Najee Harris",
      age: 24,
      position: "Running back",
      team: "Pittsburgh Steelers",
      rating: 14,
      passing: 0,
      receiving: 229,
      rushing: 1034,
      fumbles: 3,
      tackles: 0,
      interceptions: 0,
      touchdowns: 10,
    },
    {
      name: "Tony Pollard",
      age: 25,
      position: "Running back",
      team: "Dallas Cowboys",
      rating: 15,
      passing: 0,
      receiving: 371,
      rushing: 1007,
      fumbles: 0,
      tackles: 0,
      interceptions: 0,
      touchdowns: 12,
    },
    {
      name: "Dameon Pierce",
      age: 23,
      position: "Running back",
      team: "Houston Texans",
      rating: 16,
      passing: 0,
      receiving: 165,
      rushing: 939,
      fumbles: 4,
      tackles: 0,
      interceptions: 0,
      touchdowns: 5,
    },
    {
      name: "Austin Ekeler",
      age: 27,
      position: "Running back",
      team: "Los Angeles Chargers",
      rating: 16,
      passing: 0,
      receiving: 722,
      rushing: 915,
      fumbles: 5,
      tackles: 0,
      interceptions: 0,
      touchdowns: 18,
    },
    {
      name: "D'Onta Foreman",
      age: 26,
      position: "Running back",
      team: "Carolina Panthers",
      rating: 17,
      passing: 0,
      receiving: 26,
      rushing: 914,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 5,
    },
    {
      name: "Alvin Kamara",
      age: 27,
      position: "Running back",
      team: "New Orleans Saints",
      rating: 18,
      passing: 0,
      receiving: 490,
      rushing: 897,
      fumbles: 4,
      tackles: 0,
      interceptions: 0,
      touchdowns: 4,
    },
    {
      name: "Raheem Mostert",
      age: 30,
      position: "Running back",
      team: "Miami Dolphins",
      rating: 18,
      passing: 0,
      receiving: 202,
      rushing: 891,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 5,
    },
    {
      name: "Ezekiel Elliott",
      age: 27,
      position: "Running back",
      team: "Dallas Cowboys",
      rating: 19,
      passing: 0,
      receiving: 92,
      rushing: 876,
      fumbles: 0,
      tackles: 0,
      interceptions: 0,
      touchdowns: 12,
    },
    {
      name: "Johnathan Taylor",
      age: 24,
      position: "Running back",
      team: "Indianapolis Colts",
      rating: 20,
      passing: 0,
      receiving: 143,
      rushing: 861,
      fumbles: 3,
      tackles: 0,
      interceptions: 0,
      touchdowns: 4,
    },
    {
      name: "Jeff Wilson Jr.",
      age: 26,
      position: "Running back",
      team: "Miami Dolphins",
      rating: 21,
      passing: 0,
      receiving: 185,
      rushing: 860,
      fumbles: 3,
      tackles: 0,
      interceptions: 0,
      touchdowns: 6,
    },
    {
      name: "Isiah Pachecho",
      age: 23,
      position: "Running back",
      team: "Kansas City Chiefs",
      rating: 22,
      passing: 0,
      receiving: 130,
      rushing: 830,
      fumbles: 4,
      tackles: 0,
      interceptions: 0,
      touchdowns: 5,
    },
    {
      name: "Devin Singletary",
      age: 25,
      position: "Running back",
      team: "Buffalo Bills",
      rating: 23,
      passing: 0,
      receiving: 280,
      rushing: 819,
      fumbles: 3,
      tackles: 0,
      interceptions: 0,
      touchdowns: 6,
    },
    {
      name: "Joe Mixon",
      age: 26,
      position: "Running back",
      team: "Cincinnati Bengals",
      rating: 24,
      passing: 0,
      receiving: 441,
      rushing: 814,
      fumbles: 0,
      tackles: 0,
      interceptions: 0,
      touchdowns: 9,
    },
    {
      name: "David Montgomery",
      age: 25,
      position: "Running back",
      team: "Chicago Bears",
      rating: 25,
      passing: 0,
      receiving: 316,
      rushing: 801,
      fumbles: 2,
      tackles: 0,
      interceptions: 0,
      touchdowns: 6,
    },
    {
      name: "Brian Robinson Jr.",
      age: 23,
      position: "Running back",
      team: "Washington Commanders",
      rating: 26,
      passing: 0,
      receiving: 60,
      rushing: 797,
      fumbles: 2,
      tackles: 0,
      interceptions: 0,
      touchdowns: 3,
    },
    {
      name: "Cam Akers",
      age: 23,
      position: "Running back",
      team: "Los Angeles Rams",
      rating: 27,
      passing: 0,
      receiving: 117,
      rushing: 786,
      fumbles: 2,
      tackles: 0,
      interceptions: 0,
      touchdowns: 7,
    },
    {
      name: "James Conner",
      age: 2,
      position: "Running back",
      team: "Arizona Cardinals",
      rating: 28,
      passing: 0,
      receiving: 300,
      rushing: 782,
      fumbles: 3,
      tackles: 0,
      interceptions: 0,
      touchdowns: 8,
    },
    {
      name: "AJ Dillon",
      age: 24,
      position: "Running back",
      team: "Green Bay Packers",
      rating: 29,
      passing: 0,
      receiving: 206,
      rushing: 770,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 7,
    },
    {
      name: "Latavius Murray",
      age: 33,
      position: "Running back",
      team: "Denver Broncos",
      rating: 30,
      passing: 0,
      receiving: 132,
      rushing: 760,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 6,
    },
    {
      name: "Khalil Herbert",
      age: 24,
      position: "Running back",
      team: "Chicago Bears",
      rating: 31,
      passing: 0,
      receiving: 57,
      rushing: 731,
      fumbles: 0,
      tackles: 0,
      interceptions: 0,
      touchdowns: 5,
    },
    {
      name: "Cordarrelle Patterson",
      age: 31,
      position: "Running back",
      team: "Atlanta Falcons",
      rating: 32,
      passing: 0,
      receiving: 122,
      rushing: 695,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 8,
    },
    {
      name: "Leonard Fournette",
      age: 28,
      position: "Running back",
      team: "Tampa Bay Buccaneers",
      rating: 33,
      passing: 0,
      receiving: 523,
      rushing: 668,
      fumbles: 0,
      tackles: 0,
      interceptions: 0,
      touchdowns: 6,
    },
    {
      name: "Antonio Gibson",
      age: 24,
      position: "Running back",
      team: "Washington Commanders",
      rating: 34,
      passing: 0,
      receiving: 353,
      rushing: 546,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 5,
    },
    {
      name: "D'Andre Swift",
      age: 24,
      position: "Running back",
      team: "Detroit Lions",
      rating: 35,
      passing: 0,
      receiving: 389,
      rushing: 542,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 8,
    },
    {
      name: "J.K. Dobbins",
      age: 24,
      position: "Running back",
      team: "Baltimore Ravens",
      rating: 36,
      passing: 0,
      receiving: 42,
      rushing: 520,
      fumbles: 0,
      tackles: 0,
      interceptions: 0,
      touchdowns: 3,
    },
    {
      name: "James Cook",
      age: 23,
      position: "Running back",
      team: "Buffalo Bills",
      rating: 37,
      passing: 0,
      receiving: 180,
      rushing: 507,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 4,
    },
    {
      name: "Kenyan Drake",
      age: 29,
      position: "Running back",
      team: "Baltimore Ravens",
      rating: 38,
      passing: 0,
      receiving: 89,
      rushing: 482,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 5,
    },
    {
      name: "Rachaad White",
      age: 24,
      position: "Running back",
      team: "Tampa Bay Buccaneers",
      rating: 39,
      passing: 0,
      receiving: 290,
      rushing: 481,
      fumbles: 3,
      tackles: 0,
      interceptions: 0,
      touchdowns: 3,
    },
    {
      name: "Kareem Hunt",
      age: 27,
      position: "Running back",
      team: "Cleveland Browns",
      rating: 40,
      passing: 0,
      receiving: 210,
      rushing: 468,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 4,
    },
    {
      name: "Chuba Hubbard",
      age: 23,
      position: "Running back",
      team: "Carolina Panthers",
      rating: 41,
      passing: 0,
      receiving: 171,
      rushing: 466,
      fumbles: 2,
      tackles: 0,
      interceptions: 0,
      touchdowns: 2,
    },
    {
      name: "Breece Hall",
      age: 21,
      position: "Running back",
      team: "New York Jets",
      rating: 42,
      passing: 0,
      receiving: 218,
      rushing: 463,
      fumbles: 1,
      tackles: 0,
      interceptions: 0,
      touchdowns: 4,
    },
    {
      name: "Justin Jefferson",
      age: 28,
      position: "Wide Receiver",
      team: "Minnesota Vikings",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Tyreek Hill",
      age: 28,
      position: "Wide Receiver",
      team: "Miami Dolphins",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Davante Adams",
      age: 28,
      position: "Wide Receiver",
      team: "Las Vegas Raiders",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "A.J. Brown",
      age: 28,
      position: "Wide Receiver",
      team: "Philadelphia Eagles",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Stefon Diggs",
      age: 28,
      position: "Wide Receiver",
      team: "Buffalo Bills",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "CeeDee Lamb",
      age: 28,
      position: "Wide Receiver",
      team: "Dallas Cowboys",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Jaylen Waddle",
      age: 28,
      position: "Wide Receiver",
      team: "Miami Dolphins",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Devonta Smith",
      age: 28,
      position: "Wide Receiver",
      team: "Philadelphia Eagles",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Terry McLaurin",
      age: 28,
      position: "Wide Receiver",
      team: "Washington Commanders",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Amon-Ra St. Brown",
      age: 28,
      position: "Wide Receiver",
      team: "Detroit Lions",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Amari Cooper",
      age: 28,
      position: "Wide Receiver",
      team: "Cleveland Browns",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Mike Evans",
      age: 28,
      position: "Wide Receiver",
      team: "Tampa Bay Buccaneers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Christian Kirk",
      age: 28,
      position: "Wide Receiver",
      team: "Jacksonville Jaguars",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Garrett Wilson",
      age: 28,
      position: "Wide Receiver",
      team: "New York Jets",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "DK Metcalf",
      age: 28,
      position: "Wide Receiver",
      team: "Seattle Seahawks",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Ja'Marr Chase",
      age: 28,
      position: "Wide Receiver",
      team: "Cincinnati Bengals",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Chris Olave",
      age: 28,
      position: "Wide Receiver",
      team: "New Orleans Saints",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Tyler Lockett",
      age: 28,
      position: "Wide Receiver",
      team: "Seattle Seahawks",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Tee Higgins",
      age: 28,
      position: "Wide Receiver",
      team: "Cincinnati Bengals",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Chris Godwin",
      age: 28,
      position: "Wide Receiver",
      team: "Tampa Bay Buccaneers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Brandon Ayiuk",
      age: 28,
      position: "Wide Receiver",
      team: "San Francisco 49ers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Jerry Jeudy",
      age: 28,
      position: "Wide Receiver",
      team: "Denver Broncos",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "JuJu Smith-Schuster",
      age: 28,
      position: "Wide Receiver",
      team: "Kansas City Chiefs",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Michael Pittman Jr.",
      age: 28,
      position: "Wide Receiver",
      team: "Indianapolis Colts",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Mike Williams",
      age: 28,
      position: "Wide Receiver",
      team: "Los Angeles Chargers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "DJ Moore",
      age: 28,
      position: "Wide Receiver",
      team: "Carolina Panthers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Diontae Johnson",
      age: 28,
      position: "Wide Receiver",
      team: "Pittsburgh Steelers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Drake London",
      age: 28,
      position: "Wide Receiver",
      team: "Atlanta Falcons",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Donovan Peoples-Jones",
      age: 28,
      position: "Wide Receiver",
      team: "Cleveland Browns",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Gabe Davis",
      age: 28,
      position: "Wide Receiver",
      team: "Buffalo Bills",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Courtland Sutton",
      age: 28,
      position: "Wide Receiver",
      team: "Denver Broncos",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Zay Jones",
      age: 28,
      position: "Wide Receiver",
      team: "Jacksonville Jaguars",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Cooper Kupp",
      age: 28,
      position: "Wide Receiver",
      team: "Las Vegas Rams",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Jakobi Meyers",
      age: 28,
      position: "Wide Receiver",
      team: "New England Patriots",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "George Pickens",
      age: 28,
      position: "Wide Receiver",
      team: "Pittsburgh Steelers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Allen Lazard",
      age: 28,
      position: "Wide Receiver",
      team: "Green Bay Packers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Joshua Palmer",
      age: 28,
      position: "Wide Receiver",
      team: "Los Angeles Chargers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Tyler Boyd",
      age: 28,
      position: "Wide Receiver",
      team: "Cincinnati Bengals",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Keenan Allen",
      age: 28,
      position: "Wide Receiver",
      team: "Los Angeles Chargers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Darius Slayton",
      age: 28,
      position: "Wide Receiver",
      team: "New York Giants",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "DeAndre Hopkins",
      age: 28,
      position: "Wide Receiver",
      team: "Arizona Cardinals",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Adam Thielen",
      age: 28,
      position: "Wide Receiver",
      team: "Minnesota Vikings",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Marquise Brown",
      age: 28,
      position: "Wide Receiver",
      team: "Arizona Cardinals",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Brandin Cooks",
      age: 28,
      position: "Wide Receiver",
      team: "Houston Texans",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Mack Hollins",
      age: 28,
      position: "Wide Receiver",
      team: "Las Vegas Raiders",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Marquez Valdez-Scantling",
      age: 28,
      position: "Wide Receiver",
      team: "Kansas City Chiefs",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Curtis Samuel",
      age: 28,
      position: "Wide Receiver",
      team: "Washington Commanders",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "K.J. Osborn",
      age: 28,
      position: "Wide Receiver",
      team: "Minnesota Vikings",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Deebo Samuel",
      age: 28,
      position: "Wide Receiver",
      team: "San Francisco 49ers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Parris Campbell",
      age: 28,
      position: "Wide Receiver",
      team: "Indianapolis Colts",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Kalif Raymond",
      age: 28,
      position: "Wide Receiver",
      team: "Detroit Lions",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Christian Watson",
      age: 28,
      position: "Wide Receiver",
      team: "Green Bay Packers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Alec Pierce",
      age: 28,
      position: "Wide Receiver",
      team: "Indianapolis Colts",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Travis Kelce",
      age: 28,
      position: "Tight End",
      team: "Kansas City Chiefs",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "T.J. Hockenson",
      age: 28,
      position: "Tight End",
      team: "Minnesota Vikings",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Mark Andrews",
      age: 28,
      position: "Tight End",
      team: "Baltimore Ravens",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Evan Engram",
      age: 28,
      position: "Tight End",
      team: "Jacksonville Jaguars",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "George Kittle",
      age: 28,
      position: "Tight End",
      team: "San Francisco 49ers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Pat Freiermuth",
      age: 28,
      position: "Tight End",
      team: "Pittsburgh Steelers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Dallas Goedert",
      age: 28,
      position: "Tight End",
      team: "Philadelphia Eagles",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "David Njoku",
      age: 28,
      position: "Tight End",
      team: "Cleveland Browns",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Tyler Higbee",
      age: 28,
      position: "Tight End",
      team: "Los Angeles Rams",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Dalton Schultz",
      age: 28,
      position: "Tight End",
      team: "Dallas Cowboys",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Gerald Everett",
      age: 28,
      position: "Tight End",
      team: "Los Angeles Chargers",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Tyler Conklin",
      age: 28,
      position: "Tight End",
      team: "New York Jets",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Cole Kmet",
      age: 28,
      position: "Tight End",
      team: "Chicago Bears",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Dawson Knox",
      age: 28,
      position: "Tight End",
      team: "Buffalo Bills",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Hunter Henry",
      age: 28,
      position: "Tight End",
      team: "New England Patriots",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    {
      name: "Juwan Johnson",
      age: 28,
      position: "Tight End",
      team: "New Orleans Saints",
      rating: 95,
      passing: 4113,
      receiving: 0,
      rushing: 0,
      fumbles: 0,
      tackles: 0,
      interceptions: 8,
      touchdowns: 25,
    },
    
    
    
  ];

await Team.deleteMany()
const teamResponse = await Team.insertMany(teams);
players[0].teamId = teamResponse[0]._id
players[1].teamId = teamResponse[1]._id
players[2].teamId = teamResponse[2]._id

console.log(players)


await Player.deleteMany()
const playerResponse = await Player.insertMany(players);
  
}


run();
